site_name: Docs

# Plugins and extensions
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

# Theme and look
theme:
  name: material
  icon:
    logo: material/sprout
  favicon: https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/material/templates/.icons/material/sprout.svg
  features:
    - navigation.sections
    - navigation.expand
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: green
copyright: Copyright &copy; 2016 - 2024 Green Sprout

# Footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      name: Link to our GitHub
      link: https://github.com/green-sprout
    - icon: material/post
      name: Our Blog
      link: https://github.com/green-sprout/blog/discussions

# Navigation
nav:
- Home: index.md
- UCRS Filter Map: docs/general/UCRS_FilterMap.md
- SRS: docs/general/srs.md
- Sprintmeetings:
  - Sprint 2: docs/sprintmeetings/sprint2.md
